"""Compilation and deployment utilities for CoreForge-UI."""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Dict, Optional

from utils.helpers import ensure_directory


class ModelCompiler:
    """
    Merge PEFT adapters and convert the result into a GGUF artifact.
    """

    def __init__(self, output_dir: str | Path = "outputs") -> None:
        self.output_dir = ensure_directory(output_dir)

    def _resolve_base_model(self, model_name: str) -> str:
        from components.trainer import BASE_MODELS

        return BASE_MODELS.get(model_name, model_name)

    def _run_command(self, command: list[str], cwd: Path) -> subprocess.CompletedProcess:
        if not command:
            raise RuntimeError("Attempted to run an empty command.")
        return subprocess.run(
            command,
            cwd=str(cwd),
            check=True,
            text=True,
            capture_output=True,
        )

    def find_converter(self) -> Optional[Path]:
        candidate = os.environ.get("LLAMA_CPP_CONVERT")
        if candidate:
            candidate_path = Path(candidate)
            if candidate_path.exists():
                return candidate_path

        env_bin = shutil.which("convert-hf-to-gguf.py")
        if env_bin:
            return Path(env_bin)

        local_candidates = [
            Path.home() / "llama.cpp" / "convert-hf-to-gguf.py",
            Path.cwd() / "llama.cpp" / "convert-hf-to-gguf.py",
        ]
        for path in local_candidates:
            if path.exists():
                return path
        return None

    def merge_adapter(self, base_model: str, adapter_dir: str | Path) -> Path:
        """
        Merge PEFT weights into a fresh full fp16 model checkpoint.
        """
        from peft import PeftModel
        from transformers import AutoModelForCausalLM

        resolved_model = self._resolve_base_model(base_model)
        adapter_path = Path(adapter_dir)
        if not adapter_path.exists():
            raise FileNotFoundError(f"Adapter directory not found: {adapter_path}")

        merged_dir = self.output_dir / "merged"
        ensure_directory(merged_dir)

        model = AutoModelForCausalLM.from_pretrained(
            resolved_model,
            torch_dtype="auto",
            device_map="cpu",
        )
        merged_model = PeftModel.from_pretrained(model, str(adapter_path))
        merged_model = merged_model.merge_and_unload()
        merged_model.save_pretrained(str(merged_dir))
        return merged_dir

    def compile_to_gguf(
        self,
        base_model: str,
        adapter_dir: str | Path,
        quantization: str = "Q4_K_M",
        workspace: Optional[str | Path] = None,
    ) -> Dict[str, str]:
        """
        Convert merged checkpoint into GGUF.
        """
        if not quantization:
            quantization = "Q4_K_M"
        ws = ensure_directory(workspace or self.output_dir)
        merged_path = self.merge_adapter(base_model=base_model, adapter_dir=adapter_dir)
        gguf_path = Path(ws) / f"{Path(adapter_dir).name}-{quantization.lower()}.gguf"
        converter = self.find_converter()
        if converter is None:
            # Lightweight fallback for environments where llama.cpp is absent.
            # We keep behavior explicit and do not produce synthetic binaries.
            raise FileNotFoundError(
                "Cannot locate llama.cpp conversion script. "
                "Install llama.cpp and set LLAMA_CPP_CONVERT to convert-hf-to-gguf.py"
            )

        command = [
            sys.executable,
            str(converter),
            str(merged_path),
            "--outfile",
            str(gguf_path),
            "--outtype",
            quantization.lower(),
        ]
        compile_proc = self._run_command(command, cwd=Path(ws))
        return {
            "merged_path": str(merged_path.resolve()),
            "gguf_path": str(gguf_path.resolve()),
            "converter": str(converter),
            "stdout": compile_proc.stdout,
        }

    def write_modelfile(self, gguf_path: str | Path, model_alias: str = "coreforge-model") -> Path:
        path = ensure_directory(self.output_dir) / "Modelfile"
        gguf = Path(gguf_path).resolve()
        if not gguf.exists():
            raise FileNotFoundError(f"GGUF file not found: {gguf}")

        content = "\n".join(
            [
                f'FROM "{gguf}"',
                'TEMPLATE "{{ .Prompt }}"',
                'PARAMETER temperature 0.2',
                'PARAMETER top_p 0.9',
                f'SYSTEM "Model alias: {model_alias}"',
                'SYSTEM "Generated by CoreForge-UI GGUF export pipeline."',
            ]
        )
        path.write_text(content + "\n", encoding="utf-8")
        return path

    def deploy_to_ollama(self, modelfile: str | Path, model_name: str = "coreforge-model") -> str:
        modelfile = Path(modelfile)
        if not modelfile.exists():
            raise FileNotFoundError(f"Modelfile missing: {modelfile}")

        if not shutil.which("ollama"):
            raise FileNotFoundError("Ollama CLI is not installed or not on PATH.")

        self._run_command(
            ["ollama", "create", model_name, "-f", str(modelfile.name)],
            cwd=modelfile.parent,
        )
        return f"ollama:{model_name} created successfully."
